In [34]:
import sqlite3 #imports sqlite3 tool
import pandas as pd #imports pandas with the pd nickname
conn = sqlite3.connect('my_data.db') #creates a database and connects sqlite3 to it
cursor = conn.cursor() #creates a cursor

**Task 1 - Sales**

In [23]:
#Display sale_date, product, and price from the sales table.
pd.read_csv('sales.csv').to_sql('sales', conn, if_exists = 'replace', index = False) #reads in the sales csv file and connects to sql

pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''', conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

**Task 2 - HR**

In [29]:
#Find employees in Chicago with more than 10 years of experience using WHERE and AND.
pd.read_csv('hr_employees.csv').to_sql('employees', conn, if_exists = 'replace', index = False) #reads in the hr_employee csv file and connects to sql

pd.read_sql_query('''
SELECT name, city, department, salary
FROM employees
WHERE city = 'Chicago' and years_experience > 10
''', conn) #shows employees from Chicago with more then 10 years of experience

   name     city  department  salary
0  Lily  Chicago  Operations   56000

**Task 3 - Real Estate**

In [28]:
#Display the three largest properties by square footage using ORDER BY and LIMIT.
pd.read_csv('realestate_listings.csv').to_sql('listings', conn, if_exists = 'replace', index = False) #reads in the real estate csv file and connects to sql

pd.read_sql_query('''
SELECT listing_id, neighborhood, sqft, list_price
FROM listings
ORDER BY sqft DESC
LIMIT 3
''', conn) #selects the needed columns from the query and shows top 3 ordering them by sqft in descending order

   listing_id neighborhood  sqft  list_price
0         204    Riverside  3736      979000
1         206  Maple Grove  3693     1001000
2         209  Maple Grove  3499      661000

**Task 4 - Marketing**

In [33]:
#Calculate total weekly impressions using SUM() and GROUP BY. Adding in total spend by week as well to give an impression of spend ROI
pd.read_csv('marketing_campaigns.csv').to_sql('campaigns', conn, if_exists = 'replace', index = False)

pd.read_sql_query('''
SELECT week, SUM(impressions) AS total_impressions, SUM(spend) AS total_spend
FROM campaigns
GROUP BY week
''', conn)

   week  total_impressions  total_spend
0     1             181454      8960.11
1     2              74972      3319.29
2     3             193242     10526.89
3     4             180795     10325.74
4     5             264615     10403.87
5     6             229892     14387.20
6     7             235470     14301.07
7     8             253354     12213.08

**Task 5 - Restaurant**

In [41]:
#Find dates when total restaurant sales exceeded $400.
pd.read_csv('restaurant_orders.csv').to_sql('orders', conn, if_exists = 'replace', index = False)

pd.read_sql_query('''
SELECT order_date, SUM(order_total) AS total_revenue
FROM orders
GROUP BY order_date
HAVING SUM(order_total) > 400
''', conn)

   order_date  total_revenue
0  2026-10-02         492.14
1  2026-10-05         850.10
2  2026-10-07         415.94
3  2026-10-12         633.98

**Task 6 - Healthcare**

In [46]:
#Find the average patient age and longest waiting time for each doctor.
pd.read_csv('clinic_visits.csv').to_sql('visits', conn, if_exists = 'replace', index = False)

pd.read_sql_query('''
SELECT COUNT(*) AS total_visits,
ROUND(AVG(patient_age), 1) AS avg_patient_age,
MAX(wait_minutes) AS longest_wait
FROM visits
''', conn)

   total_visits  avg_patient_age  longest_wait
0            35             45.4            75

**Task 7 - Banking**

In [56]:
#Join customer and transaction tables to calculate total transaction amounts by branch.
pd.read_csv('bank_customers.csv').to_sql('customers', conn, if_exists = 'replace', index = False)
pd.read_csv('bank_transactions.csv').to_sql('transactions', conn, if_exists = 'replace', index = False)

pd.read_sql_query('''
SELECT c.branch, SUM(t.amount) AS total_transactions
FROM transactions AS t
JOIN customers AS c ON t.customer_id = c.customer_id
GROUP BY c.branch
''', conn)

      branch  total_transactions
0    Airport            15177.98
1    Main St             3581.19
2  Northgate            19546.49
3   Westside            13996.30

In [57]:
conn.close()